# Generated by Django 5.1 on 2024-09-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userinterestcategoryranking_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInterestCategoryRanking',
            new_name='UserInterestCategoryImportance',
        ),
    ]
