# Generated by Django 5.1 on 2024-10-02 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_userinterestcategoryranking_userinterestcategoryimportance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterestcategoryimportance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_category_importances', to=settings.AUTH_USER_MODEL),
        ),
    ]
