# Generated by Django 5.1 on 2024-10-23 00:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_userinterestcategoryimportance_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
