# Generated by Django 5.1 on 2024-10-23 00:14

import uuid
from django.db import migrations


def gen_uuid(apps, _):
    CustomUser = apps.get_model("core", "CustomUser")
    for user in CustomUser.objects.all():
        user.public_id = uuid.uuid4()
        user.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_customuser_public_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
