# Generated by Django 5.1 on 2024-10-23 00:14
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20241023_0014"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
